resolver: lts-8.18
packages:
- '.'
- location: '/home/mitchell/haskell/yi/'
  subdirs:
    - yi-core
    - yi-frontend-vty
    - yi-keymap-vim
    - yi-language
    - yi-misc-modes
    - yi-mode-haskell
extra-deps:
  - yi-rope-0.10
